#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WebRtc.Mono.Droid.Resource", IsApplication=true)]

namespace WebRtc.Mono.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int logo = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int LinearLayout02 = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int LinearLayout03 = 2131034137;
			
			// aapt resource value: 0x7f050001
			public const int TextView01 = 2131034113;
			
			// aapt resource value: 0x7f050017
			public const int TextView02 = 2131034135;
			
			// aapt resource value: 0x7f050000
			public const int TextView03 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int btExit = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int btStartStopCall = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int btSwitchCamera = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int cbAECM = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int cbAutoGainControl = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int cbDebugRecording = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int cbLoopback = 2131034133;
			
			// aapt resource value: 0x7f05002b
			public const int cbNack = 2131034155;
			
			// aapt resource value: 0x7f050007
			public const int cbNoiseSuppression = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int cbSpeaker = 2131034121;
			
			// aapt resource value: 0x7f050016
			public const int cbStats = 2131034134;
			
			// aapt resource value: 0x7f05002c
			public const int cbVideoRTPDump = 2131034156;
			
			// aapt resource value: 0x7f050012
			public const int cbVideoReceive = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int cbVideoSend = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int cbVoice = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int cbVoiceRTPDump = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int etARxPort = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int etATxPort = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int etRemoteIp = 2131034136;
			
			// aapt resource value: 0x7f05002a
			public const int etVRxPort = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int etVTxPort = 2131034153;
			
			// aapt resource value: 0x7f05001e
			public const int image = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int ivPreview = 2131034145;
			
			// aapt resource value: 0x7f05000c
			public const int llLocalView = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int llRemoteView = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int radio_group1 = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int radio_mediacodec = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int radio_opengl = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int radio_surface = 2131034140;
			
			// aapt resource value: 0x7f050028
			public const int spCodecSize = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int spCodecType = 2131034150;
			
			// aapt resource value: 0x7f050002
			public const int spVoiceCodecType = 2131034114;
			
			// aapt resource value: 0x7f05001f
			public const int spinner_row = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int svLocal = 2131034144;
			
			// aapt resource value: 0x7f050025
			public const int tab_aconfig = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int tab_config = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int tab_vconfig = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int tab_video = 2131034146;
			
			// aapt resource value: 0x7f050027
			public const int tvCodecSize = 2131034151;
			
			// aapt resource value: 0x7f050011
			public const int tvTitle = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aconfig = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int both = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int send = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int tabhost = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int vconfig = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040018
			public const int AECM = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int AutoGainControl = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int NoiseSuppression = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int VoiceActivityDetection = 2130968599;
			
			// aapt resource value: 0x7f040015
			public const int aRxPort = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int aTxPort = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04001c
			public const int backCamera = 2130968604;
			
			// aapt resource value: 0x7f040006
			public const int codecSize = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int codecType = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int codectype_prompt = 2130968579;
			
			// aapt resource value: 0x7f040021
			public const int debugrecording = 2130968609;
			
			// aapt resource value: 0x7f040004
			public const int demoTitle = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int enableVideoReceive = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int enableVideoSend = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int enableVoice = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int error = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int errorCamera = 2130968578;
			
			// aapt resource value: 0x7f04001f
			public const int exit = 2130968607;
			
			// aapt resource value: 0x7f04001b
			public const int frontCamera = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int gSettings = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int loopback = 2130968584;
			
			// aapt resource value: 0x7f040024
			public const int mediacodec = 2130968612;
			
			// aapt resource value: 0x7f04001a
			public const int nack = 2130968602;
			
			// aapt resource value: 0x7f040025
			public const int opengl = 2130968613;
			
			// aapt resource value: 0x7f040007
			public const int remoteIp = 2130968583;
			
			// aapt resource value: 0x7f040022
			public const int rtpdump = 2130968610;
			
			// aapt resource value: 0x7f040020
			public const int speaker = 2130968608;
			
			// aapt resource value: 0x7f04000c
			public const int startBoth = 2130968588;
			
			// aapt resource value: 0x7f04001d
			public const int startCall = 2130968605;
			
			// aapt resource value: 0x7f04000a
			public const int startListen = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int startSend = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int stats = 2130968585;
			
			// aapt resource value: 0x7f04001e
			public const int stopCall = 2130968606;
			
			// aapt resource value: 0x7f040023
			public const int surfaceview = 2130968611;
			
			// aapt resource value: 0x7f040013
			public const int vRxPort = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int vSettings = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int vTxPort = 2130968594;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
